### ISSUE TITLE
Fix zeroconf registration on senicos

### ISSUE THREAD

**Issue by tomster** [getsenic/senic-hub#160]
while avahi is installed and configured (there's an entry in the output from `ps` like `avahi-daemon: registering [senic-hub-beta.local]` the actual resolution does not work. neither locally nor from other hosts.

**Comment by tomster** [comment]
update: this is still the case but we have decided to put the whole zeroconf feature on hold as it's not really providing much benefit for end users.

**Comment by neelotpalnag** [comment]
Zeroconf is now working and has been configured to respond to API calls to the backend (on port 6543) as well. Is there anything else that has to be taken care of now?
