### ISSUE TITLE
Bluenet BLE service not found on devices running Android 5.1

### ISSUE THREAD

**Issue by luminosuslight** [getsenic/senic-hub#170]
The custom Bluetooth Low Energy GATT service that Bluenet is advertising for Wifi provisioning is not showing up on multiple devices running Android 5.1. Instead two default services are shown.

This can be observed in both the React Native app and Nordic Semiconductor nRF Connect app, so it is probably not a problem in the app itself.
Bluetooth LE and 128 bit UUIDs in general can be eliminated as the possible issue, too, as these are working on at least one of these devices (Nuimos can be connected).
The output of logcat is identical to successfully connecting to a Nuimo.

Known problematic devices:
* Huawei Mate S running Android 5.1.1
* @grunskis phone? - Fairphone 2 with Android 5.1

Unsolved Stackoverflow question with the same problem: [Here](https://stackoverflow.com/questions/38002948/android-ble-custom-service-uuid-not-finding)

**Comment by luminosuslight** [comment]
Together with a user on IRC I finally found a solution!

The problem is that Android 5.1 devices try to connect with BR/EDR if it is advertised as supported and then aren't able to find the custom service anymore.
One solution would be not to advertise BR/EDR, but at the moment we cannot change this with BlueZ as far as I know.
The workaround is to disable BR/EDR for the Bluetooth adapter of the hub in general with the following commands:

```
btmgmt power on
btmgmt bredr off
btmgmt power on
```

**Comment by larsblumberg** [comment]
Great find! Here's a way to explicitly require a BLE connection, in case this issue is related:

https://code.google.com/p/android/issues/detail?id=223104

The hack is implemented in our Android SDK:

https://github.com/getsenic/nuimo-android/blob/master/nuimo/src/main/kotlin/com/senic/nuimo/NuimoBluetoothController.kt#L105

**Comment by luminosuslight** [comment]
@larsblumberg I think the problem with Android 7.0 is different (BR/EDR is not even advertised in that case) but the fix could be working anyway.

@tomster Until we can add and test the fix in the Android app, can we disable BR/EDR in Senic OS as it is not used at the moment? Either with the commands from above or with the main.conf settings file of BlueZ (see https://github.com/RadiusNetworks/bluez/blob/master/src/main.conf#L53) ?
