### ISSUE TITLE
Don't log Wi-Fi network password

### ISSUE THREAD

**Issue by grunskis** [getsenic/senic-hub#171]
I've noticed that Bluenet logs password when it receives it from the client. This shouldn't be logged to respect users privacy.

**Comment by luminosuslight** [comment]
Wifi password will only be logged when debugging (with -vv option) in #181

**Comment by luminosuslight** [comment]
Todo: make sure Bluenet is not started with -vv but only with -v option in production setup (i.e. change it in senic-hub/deployment/roles/hub-ubuntu/templates/bluenet_supervisor.conf ?).

**Comment by grunskis** [comment]
Yep, that's where the change should be added.

**Comment by rudolfs** [comment]
This is already done.
