### ISSUE TITLE
Allow %IP placeholder in bluenet's host name that gets replaced with IP address

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#172]
Bluenet has a host name parameter `-h` that can be feeded with the hostname or IP address of the hub. Since currently we don't use a zeroconf for the hub, we want the Hub to tell us its IP address. Therefor the `-h` parameter should replace occurrences of `%IP` with the actual IP address when connected to a Wi-Fi network. This said, we can feed the `-h` with any arbitrary content such as `-h http://%IP:6543/-/` to let the mobile client know where the hub is reachable. Currently we provide the hub's full API endpoint to the `-h` parameter for convenience.

**Comment by luminosuslight** [comment]
Implemented in #181
