### ISSUE TITLE
Bluenet stops sending notifications when Nuimo disconnects

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#175]
We also receive "device disconnect" events when a Nuimo controller disconnects. When this happens, bluenet stops sending notifications.

@luminosuslight I will start looking into this issue today, let me see how far I can get. Maybe you want to take over later.

**Comment by luminosuslight** [comment]
We found out that it is not possible to connect the setup app and a Nuimo at the same time to the hub. This means that we can assume that each device connected to the hub while Bluenet is running is a setup app and this issue is not relevant anymore.
