### ISSUE TITLE
Nuimo App doesn't start properly if Sonos speaker isn't reachable via it's IP address

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#204]
Can be easily reproduced by adding a section to `nuimo_app.cfg` such as:

```
[deadbeef]
type = sonos
id = deadbeef
device_ids = deadbeaf-1
ip_address = 192.168.1.23
```

Make sure that there's actually no device/speaker with that IP address.

**Comment by neelsenic** [comment]
I reckon this issue has been solved in PR #290 , where the fix has been applied to all kinds of devices being controlled over the wifi network.
