### ISSUE TITLE
nuimo_app logging doesn't work

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#207]
All logging statements from nuimo_app should land in the nuimo_app.log file.
So far only print (stdout) statements land there. Something is awry in the production.ini file, because logger.warn and logger.error should go in the log file as well.

**Comment by luminosuslight** [comment]
At least the output of `supervisorctl tail -f nuimo_app` is fixed for me by replacing line 26 in `nuimo_app/__main__.py`:
```
logger.setLevel(logging.DEBUG)
```
with
```
log_format = '%(asctime)s %(levelname)-5.5s [%(name)s] %(message)s'
logging.basicConfig(level=logging.DEBUG, format=log_format)
```

**Comment by luminosuslight** [comment]
We decided to go with
```
log_format = '%(asctime)s %(levelname)-5.5s [%(name)s] %(message)s'
logging.basicConfig(level=logging.DEBUG, format=log_format)
```
for now.
