### ISSUE TITLE
Building setup-app on Linux fails

### ISSUE THREAD

**Issue by luminosuslight** [getsenic/senic-hub#214]
The method [`getPassword()` in build.gradle](https://github.com/getsenic/senic-hub/blob/master/senic_hub/setup_app/android/app/build.gradle#L105) doesn't work on Linux.
It is used to get the password for the keystore interactively on the commandline to sign the app.

A workaround is to not use the method and instead either hardcoding the password or setting it to an empty string (app can't be signed then): `def password = "" //getPassword("android_keystore")`.

**Comment by rudolfs** [comment]
We only support OS X for now.
