### ISSUE TITLE
Assert that commented out mocks got called in test_device_discovery.py

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#230]
We have some tests that shall assert whether some methods had been called. Therefore we use mocks and the `mock.assert_called_once()` method. `assert_called_once` is however only available in Python 3.6, our testing environment uses Python 3.5.

Either the commented-out code is back-ported to Python 3.5 or we use Python 3.6 in the future.

The commented code can be found here (with direct links to the according lines):
https://github.com/getsenic/senic-hub/pull/229/files#diff-5e3a700b278df8631d124b40d528682fR34
and here:
https://github.com/getsenic/senic-hub/pull/229/files#diff-5e3a700b278df8631d124b40d528682fR51

**Comment by neelotpalnag** [comment]
@kelada : This seems to be doing something with HomeAssistant. Should I investigate right away, or decide it's fate later?
