### ISSUE TITLE
Very seldomly, devices.json's content is contained twice

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#235]
Although we always require to replace the whole file content of devices.json, very seldomly it's actually appended instead of overwritten. This leads to the file content being contained twice.

**Comment by rudolfs** [comment]
Actually it happens all the time whenever you have a bunch of async requests hammering the backend.

Can be reproduced by launching concurrent auth requests for devices like this (replace the device ids with actual ids):
```
curl -X POST http://10.10.10.158:6543/-/setup/devices/001788176885/authenticate &
curl -X POST http://10.10.10.158:6543/-/setup/devices/001788708284/authenticate &
curl -X POST http://10.10.10.158:6543/-/setup/devices/001788708eb4/authenticate & 
```
