### ISSUE TITLE
Nuimo app needs to reload its configuration (nuimo_app.yaml) when it has changed

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#236]
The senic_hub backend can modify the `nuimo_app.yaml` configuration file while Nuimo App runs. This happens for example when the user adds or removes Nuimo app components (e.g. Sonos, Philips Hue) using the Senic Hub setup app. When the file got modified, we want Nuimo app to reload the content.

We could also simply restart `nuimp_app` process via supervisor. This would however temporarily disconnect the Hub from connected Nuimos as Nuimo App manages the Bluetooth connections to Nuimo. Nuimo App initiates the Bluetooth connection to Nuimo when started and disconnects it when the app is stopped. This said, restarting Nuimo App would be a bad user experience as Nuimo would be temporarily unusable whenever the user changes the app components.

**Comment by luminosuslight** [comment]
This was implemented in PR #233.
