### ISSUE TITLE
Support more than one Lightify light bulb to be controlled by Nuimo App

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#237]
Currently we only control the first Lightify light we receive from the Lightify gateway:

https://github.com/getsenic/senic-hub/blob/master/senic_hub/nuimo_app/components/lightify.py#L94

We actually want to let the user decide which of all lights he want to control, in analogy how we manage to control all Philips Hue lights.

**Comment by rudolfs** [comment]
We need to order more lightify lights in order to test this.
