### ISSUE TITLE
Let user remove app components from Nuimo App

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#238]
We already have an REST API end point that allows the user to remove an added app component from Nuimo App: `DELETE /-/nuimos/<MAC>/components/<ID>`.

Now we need to allow the user to remove app components using the Setup App. I.e. by long touching an app component or by swiping it.

**Comment by luminosuslight** [comment]
I started to implement this in the following branch:
https://github.com/luminosuslight/senic-hub/tree/delete-components

It uses the swipe-to-delete approach described [here](https://medium.com/@bddougie/adding-swipe-to-delete-in-react-native-cfa85a5f5a31). Maybe it would be good to support long touching, too.
Actually deleting the component is *not* yet implemented.

**Comment by luminosuslight** [comment]
This was addressed in PR #248.
