### ISSUE TITLE
WiFi related problems in setup process

### ISSUE THREAD

**Issue by rudolfs** [getsenic/senic-hub#273]
There seem to be multiple related issues with the WiFi provisioning steps.

1. after entering an invalid password once it's not possible to move forward by entering the correct password

2. going back to the WiFi listing is not possible from the password entry screen

3. the password entry form is displayed multiple times when going back to the WiFi listing screen

All of these issues should be resolved by cleaning up the underlying architecture of the WiFi provisioning steps.

**Comment by commento** [comment]
Maybe also issue #264 could be part of this issues list.
