### ISSUE TITLE
Device Discovery error

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#306]
Error traced in the `device_discovery.log`.
Seems related to `netdisco` module, in particular to `mdns`.
Error related to `Bose Soundtouch` discovery.
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/netdisco/mdns.py", line 20, in start
    self.zeroconf = zeroconf.Zeroconf()
  File "/usr/lib/python3.5/site-packages/zeroconf.py", line 1523, in __init__
    socket.inet_aton(_MDNS_ADDR) + socket.inet_aton(i))
OSError: [Errno 105] No buffer space available
```

from the Python documentation:
**socket.inet_aton(ip_string)**
Convert an IPv4 address from dotted-quad string format (for example, ‘123.45.67.89’) to 32-bit packed binary format, as a bytes object four characters in length. This is useful when conversing with a program that uses the standard C library and needs objects of type struct in_addr, which is the C type for the 32-bit packed binary this function returns.

inet_aton() also accepts strings with less than three dots; see the Unix manual page inet(3) for details.

**If the IPv4 address string passed to this function is invalid, OSError will be raised. Note that exactly what is valid depends on the underlying C implementation of inet_aton().**

inet_aton() does not support IPv6, and inet_pton() should be used instead for IPv4/v6 dual stack support.

**Comment by neelotpalnag** [comment]
@commento  : No idea on how to fix this. Lets just keep it like this for now

**Comment by neelotpalnag** [comment]
@commento  : Will be closed by a PR in the senic-os repository. This error has been fixed by updating the sysctl value : /proc/sys/net/ipv4/igmp_max_memberships to more than zero.
