### ISSUE TITLE
Add the endpoint for battery level of Nuimo

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-hub#332]
Implement the endpoint:

Example:
    http://10.10.10.125:6543/-/nuimos/{nuimo MAC address}/battery

**Comment by TheMeaningfulEngineer** [comment]
@kelada What would be the expected response for this call?

**Comment by TheMeaningfulEngineer** [comment]
Response:

    {battery_level: integer [-1 100] }

-1 represents that the device is off

**Comment by TheMeaningfulEngineer** [comment]
This is related to:

- https://github.com/getsenic/senic-hub/pull/327
- https://github.com/getsenic/senic-hub/pull/311/commits/ca60d6df833050c6b921b164def8d46d3c2f7b8b

which resulted in a bug when tested with multiple Nuimos.
Trying anew

**Comment by TheMeaningfulEngineer** [comment]
Starter implementation
https://github.com/TheMeaningfulEngineer/senic-hub/tree/nuimo-battery-endpoint

Still need to implement the checking if Nuimo is on when the request is recieved.

**Comment by neelotpalnag** [comment]
Implemented in PR #338 . Closing.
