### ISSUE TITLE
App crashing while using multiple bulbs of different kinds

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#348]
α-testing feedback

**Comment by neelotpalnag** [comment]
@kelada  : Solved ?

**Comment by kelada** [comment]
From the frontend's perspective it's fixed, however I think a proper fix needs to happen on the backend ie. devices are given default stations.

**Comment by neelotpalnag** [comment]
Is it a goodidea to reopen & re-title the issue?

**Comment by kelada** [comment]
I think this should stay closed. @commento was looking into how to handle the issue on the backend. I believe #343 is related to the core issue.
