### ISSUE TITLE
Don't Allow to proceed without authenticated Devices [App][FrontEnd]

### ISSUE THREAD

**Issue by neelotpalnag** [getsenic/senic-hub#363]
In cases when a user is adding a Nuimo, and the device discovery returns the devices, the user should not be allowed to proceed unless at least one of the devices has the status "AUTHENTICATED".
@kelada , @rudolfs - What do you say?

**Comment by kelada** [comment]
We have planned to handle this in the frontend, we can close this once we have done so.
