### ISSUE TITLE
Add room key/value to devices endpoint

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-hub#366]
When querying the ``/-/devices`` endpoint Philips Hue and Sonos devices should all have a new key/value pair, ``"room": "super-cool-place"``.

eg.
```
{
  "id": "001788176885-light-36",
  "type": "philips_hue",
  "name": "Hue color light 2",
  "room": "office 1"
}
```

This feature will be used in the device selection modal on the frontend and allow a user to easily distinguish which lights are in which Philips Hue "room" the setup from the Philips Hue Official App.

**Comment by neelotpalnag** [comment]
The logic for the same has been implemented in PR #387 . The PR a non-breaking non-interfering code. Can be safely merged, but wont serve any purpose.
