### ISSUE TITLE
org.freedesktop.networkmanager was not provided by any .service files

### ISSUE THREAD

**Issue by chirag04** [getsenic/senic-hub#372]
Running bluenet.py fails with `the name org.freedesktop.networkmanager was not provided by any .service files`. 

I have no idea what's going on here. Appreciate any pointers here.

**Comment by neelotpalnag** [comment]
Hi Chirag!
I'd suggest following these steps:
 1. Check if you have `NetworkManager.service` in `/lib/systemd/system/NetworkManager.service` and/or in `/etc/systemd/system/multi-user.target.wants/NetworkManager.service` or at any other location in `/etc/systemd/`. You may use `find . -name "NetworkManager.service"`
2.  If the `.service` file is in place, check the status of NetworkManager service using the systemd command `systemctl status NetworkManager`. If it reports `not-found`, then perform a fresh install of NetworkManager using 
```
sudo apt-get install network-manager
sudo apt-get install network-manager-gnome
sudo systemctl start NetworkManager.service

```
3. Try executing `systemctl status NetworkManager` again to check the status.

A fresh install of NetworkManager may help fix the issue. If not, please report further to us.
Cheers!
