### ISSUE TITLE
QA logging

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-hub#395]
Our current state of logging isn't helpful for doing QA. 
We're updating the logs to give QA an additional confirmation a test passed successfully.
And extending the logs with a debug level so QA can provide context information when submitting the bug.

Example of the ongoing work can be traced here on this branch:
https://github.com/getsenic/senic-hub/tree/improve-logging

**Comment by kelada** [comment]
See #403

**Comment by TheMeaningfulEngineer** [comment]
This has done what it should have, and is at the moment to generic to be acted on. Am closing it in favor of more specific issues like https://github.com/getsenic/senic-hub/issues/403
