### ISSUE TITLE
Remove unsupported platforms/devices/integrations

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-hub#398]
Please remove all integrations that aren't actively supported/tested:
- [x] Lightify (osram)
- [x] Home Assistant
- etc...

**Note:** Once removed from here, dependencies should be removed from senic-os, please make a new issue regarding on that repo

**Comment by avichalp** [comment]
This is addressed in the PR:
https://github.com/getsenic/senic-hub/pull/413
