### ISSUE TITLE
Provide more context to sentry errors

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-hub#403]
Can you provide more context to a stacktrace, more specifically:
- version of senic os
- version of Philips hue api (and if possible software version of the bridge)
- version of sonos api (and if possible software version sonos speaker)

This will allow us to spot issues around device versions changing outside of our control.

**Comment by TheMeaningfulEngineer** [comment]
@avichalp This can all go into the `improve-logging`. I'm regularly rebasing on that for the BT issue.

**Comment by avichalp** [comment]
These are interesting piece of information.
How about adding `senic-os` version in generic log formatters?
For eg: `2018-01-29 14:54:55,814 <os-version> INFO  [senic_hub.nuimo_app] gesture BATTERY LEVEL 10`

**Comment by TheMeaningfulEngineer** [comment]
Not up for that solution, seems unnecessarily redundant to have it in every log line.

**Comment by burakparim** [comment]
Having `senic-os` version on logs might be helpful I think, not now but in the future. Do you know if error rate vs battery level of a nuimo is measured? Eg., stations/ring stays idle half of the time below 15% battery... This is not hub related, but we can improve Nuimo user exp if we detect this sort of issues.

**Comment by avichalp** [comment]
@burakparim @TheMeaningfulEngineer 
I also think that `senic-os` level can be helpful in future specially when we start to support multiple os builds. Lets discuss more about merits and demerits here.

>do you know if error rate vs battery level of a nuimo is measured?
This is currently not logged. But I agree that this is a interesting use case. As you pointed out it is not related to the hub and I also would I like to take a look into it separately. If you can create a feature request on a different Github issue we can discuss about it there in more detail there.
