### ISSUE TITLE
Add NUIMO feature broken with new BT code

### ISSUE THREAD

**Issue by rudolfs** [getsenic/senic-hub#415]
It just detects the already found NUIMO again.

**Comment by TheMeaningfulEngineer** [comment]
What would you expect to happen when:
* there are no Nuimos in range
* a new Nuimo is being added

If you could describe it in terms of endpoints:
```
curl -X POST   http://10.10.10.181:6543/-/nuimos
```
that would be very helpful.

**Comment by TheMeaningfulEngineer** [comment]
Will reopen this with a specific name once it is clear what it means through the testing of the 0.1.9 version.
