### ISSUE TITLE
Add helper functions module

### ISSUE THREAD

**Issue by avichalp** [getsenic/senic-hub#425]
https://github.com/getsenic/senic-hub/blob/master/senic_hub/backend/views/appinfo.py#L28-L67

These functions here are generic and can be used at multiple places where we need the data about the os or the hardware etc. One example is we need the os version to append it to the log which we can send to sentry.

Would be good to create a module `senic_hub.backend.utils` where we can move these three functions to start with. Later we can put other utility functions here that can be used across `backend` module.

Thoughts?
CC: @rudolfs

**Comment by rudolfs** [comment]
+1

Bonus points if you put it in a class and write some tests.

**Comment by avichalp** [comment]
I can write tests around it. But did not understand why you would like to put them in a class?

**Comment by rudolfs** [comment]
I guess I'm just used to Ruby, where everything is a class. Since all of these functions are extracting information about the system I'd put them in a class that deals with just this.

Do whatever is idiomatic Python and it'll be good.

**Comment by avichalp** [comment]
initial attempt: https://github.com/getsenic/senic-hub/pull/426
