### ISSUE TITLE
Frontend is not included in the senic_hub package

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#90]
`/srv/senic_hub/venv/htdocs` is not present after installing `senic_hub` from pypi

**Comment by tomster** [comment]
That's not the intended behaviour. `htdocs` only exists as a destination for creating the pre-built documentation. only the sources are part of the package, not the built artefact, they are part of the devpi publishing process and/or can be built on-demand from the sources.

**Comment by larsblumberg** [comment]
So how do we solve that?

**Comment by tomster** [comment]
why does it need to be solved? we don't want to install pre-generated html docs when installing the egg. at least i don't know why and where to. by default all included files are kept inside the python's `lib/python/site-packages` directory which is not a place where users would look for documentation in my experience.

did you work with another python package that did that and expected this here, too or what is the source of the expectation?

**Comment by larsblumberg** [comment]
When I install the `senic_hub` package (i.e. `pip install senic_hub`) I expect the frontend files to be included. Otherwise the Senic Hub wouldn't completely work after installing the package, right?

**Comment by tomster** [comment]
right, now i understand :)

this indeed has become broken during restructuring. i fixed this now in #110
